---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-dep
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: nhanif/helloworld
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: default
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32500
  selector:
    app: helloworld
---
